# Funktionen

Def.: "someone else's code"

Haupt-Zweck: Code wiederverwendbar machen

Vorteile / Konzepte hinter einer Funktion
- math. $f(X) -> Y$, wohl-definierter Zusammenhang zwischen Inputs und Outputs
- vorgefertigter Code
- Zusammenfassen von mehreren Code Zeilen, und einen **Namen** dafür
- **Blackbox**-Prinzip => Inputs werden in Outputs gemapped, uns interessiert nicht, wie das passiert

2 Rollen:
- Autor / **Maintainer** => definiert und implementiert die Funktion
- Nutzer / **Caller** => nutzt die Funktion nur

## Built-in Funktionen

"man kann sie einfach nutzen"

In [1]:
numbers = [7, 8, 9, 1, 2, 3, 6, 5, 4, 11, 12, 10]

In [2]:
sum(numbers)

78

In [3]:
len(numbers)

12

In [4]:
max(numbers)

12

### Constructors

In [5]:
7

7

In [6]:
float(7)

7.0

In [7]:
int("7")

7

In [8]:
int("a")

ValueError: invalid literal for int() with base 10: 'a'

In [11]:
int("a", base=16)

10

## Standard Library

"erst importieren, dann nutzen"

In [12]:
import math

In [13]:
math

<module 'math' from '/opt/python/versions/3.12.0/lib/python3.12/lib-dynload/math.cpython-312-x86_64-linux-gnu.so'>

In [14]:
type(math)

module

In [15]:
math.pi

3.141592653589793

In [16]:
import random

In [31]:
random.random()

0.6576761437298932

In [37]:
pi = 42

In [38]:
pi

42

In [39]:
from math import pi

In [40]:
pi

3.141592653589793

In [35]:
import math as m

In [36]:
m.pi

3.141592653589793

## Third-party Packages / Libraries

"erst installieren, dann importieren, dann nutzen"

In [41]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [42]:
import numpy as np

In [44]:
vec = np.array([1, 2, 3])

vec

array([1, 2, 3])

In [45]:
type(vec)

numpy.ndarray

In [48]:
3 * [1, 2, 3]  # concatenation

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [49]:
3 * vec

array([3, 6, 9])

In [51]:
10 * np.array([
    [1, 2, 3],
    [4, 5, 6]
])

array([[10, 20, 30],
       [40, 50, 60]])

## Eigene Funktionen

In [52]:
numbers = [7, 8, 9, 1, 2, 3, 6, 5, 4, 11, 12, 10]

In [53]:
total = 0
count = 0

for number in numbers:
    if number % 2 == 0:
        total = total + number
        count = count + 1

average = total / count

average

7.0

In [54]:
other = [40, 41, 42, 43, 44]

In [55]:
total = 0
count = 0

for number in other:
    if number % 2 == 0:
        total = total + number
        count = count + 1

average = total / count

average

42.0

In [56]:
def average_evens(integers):
    total = 0
    count = 0

    for number in integers:
        if number % 2 == 0:
            total = total + number
            count = count + 1

    average = total / count

    return average

In [57]:
average_evens

<function __main__.average_evens(integers)>

In [58]:
type(average_evens)

function

`func()` => **call operator**

In [59]:
ergebnis = average_evens([1, 2, 3])

ergebnis

2.0

In [60]:
result = average_evens(numbers)

In [61]:
result

7.0

In [62]:
average_evens(other)

42.0

In [63]:
def average_evens(numbers):
    """Berechne den Durchschnitt aller geraden Zahlen.

    Weitere Infos.
    Zielgruppe: Nutzer der Funktion

    Args:
        numbers (list von int's): Die Zahlen, die gemittelt werden

    Returns:
        average (float)
    """
    total = 0
    count = 0

    # Kommentar: Warum macht der Code etwas?
    # Zielgruppe: Autor/Maintainer der Funktion
    # "Running Total" berechnen
    for number in numbers:
        if number % 2 == 0:
            total = total + number
            count = count + 1

    average = total / count

    return average

In [64]:
help(average_evens)

Help on function average_evens in module __main__:

average_evens(numbers)
    Berechne den Durchschnitt aller geraden Zahlen.

    Weitere Infos.
    Zielgruppe: Nutzer der Funktion

    Args:
        numbers (list von int's): Die Zahlen, die gemittelt werden

    Returns:
        average (float)



Variante: Der Durchschnitt soll skaliert werden

In [65]:
def average_evens(numbers, *, scalar=1):
    """Berechne den Durchschnitt aller geraden Zahlen.

    Args:
        numbers (list von int's): Die Zahlen, die gemittelt werden
        scalar (int oder float): Skaliert den Durchschnitt;
            standardmäßig wird nicht skaliert

    Returns:
        average (float)
    """
    total = 0
    count = 0

    for number in numbers:
        if number % 2 == 0:
            total = total + number
            count = count + 1

    average = total / count

    return scalar * average

In [66]:
average_evens([1, 2, 3])

2.0

In [67]:
average_evens([1, 2, 3], 2  # wegen *, => keyword-only arguments

SyntaxError: incomplete input (590556970.py, line 1)

In [68]:
average_evens(numbers=[1, 2, 3], scalar=2)

4.0

In [69]:
average_evens(scalar=2, numbers=[1, 2, 3])

4.0

In [70]:
average_evens([1, 2, 3], scalar=2)

4.0