In [1]:
from matrix import Matrix
from vectors import Vector

import numpy as np

In [2]:
m = Matrix(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

m

Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,)))

In [3]:
m_arr = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

m_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
v = Vector([1, 2, 3])

v

Vector((1.0, 2.0, 3.0))

In [5]:
v.as_matrix()

Matrix(((1.0,), (2.0,), (3.0,)))

In [6]:
v.as_matrix(column=True)

Matrix(((1.0,), (2.0,), (3.0,)))

In [7]:
v.as_matrix(column=False)

Matrix(((1.0, 2.0, 3.0,)))

# Methoden

## 1) Instanz Methoden

Eine Methode, die als Input einen konkreten `Vector` (also `self`) als Input benötigt

Anwendung: Matrizen transponieren

In [8]:
m_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
m_arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
m_arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
m

Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,)))

In [12]:
m.transpose()

Matrix(((1.0, 4.0,), (2.0, 5.0,), (3.0, 6.0,)))

### Computed Properties / Abgeleitete Eigenschaften

`@...` Syntax => **Decorator Syntax** => die Funktion unter ihr wird "irgendwie" modifiziert

`@property` => die Funktion wird automatisch gecalled => man muss kein `()` anhängen

Proxy Regel: Methoden, die nur von `self` abhängen sind solche "Eigenschaften"

In [13]:
m.n_rows

2

In [14]:
m.n_cols

3

In [15]:
m_arr.shape

(2, 3)

In [16]:
m.shape

(2, 3)

## 2) Klassen Methoden

Eine Methode, die ohne einen konreten `Vector` arbeiten kann

Häufige Anwendung: **Alternative Constructors**

In [17]:
Matrix(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,)))

In [18]:
Matrix.from_rows(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,)))

In [19]:
Matrix.from_cols(
    [
        [1, 4],
        [2, 5],
        [3, 6],
    ]
)

Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,)))

In [20]:
Matrix.random(n_rows=3, n_cols=3)

Matrix(((24.0, 81.0, 40.0,), (78.0, 97.0, 48.0,), (80.0, 39.0, 73.0,)))

In [21]:
Matrix.random(n_rows=3, n_cols=3, min_=-99)

Matrix(((50.0, -11.0, 50.0,), (-24.0, -92.0, -27.0,), (94.0, 66.0, -61.0,)))

## Sequenz Emulation

In [22]:
m

Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,)))

In [23]:
0 in m

False

In [24]:
2 in m

True

In [25]:
len(m)

6

Bemerkung: die Matrix hat eigentlich 2 Dimensionen => Der Loop "flattened" die Dimensionen in eine

In [26]:
for x in m:  # im Hintergrund: while-Loop mit iter(m) zu Beginn
    print(x)

1.0
2.0
3.0
4.0
5.0
6.0


In [27]:
for x in reversed(m):
    print(x)

6.0
5.0
4.0
3.0
2.0
1.0


### More on Iteration

Manchmal lohnt es sich, verschiedene Arten von Looping Verhalten zu implementieren

In [28]:
r = m.rows()

r

<generator object Matrix.rows.<locals>.<genexpr> at 0x79ac5f5b8fb0>

In [29]:
next(r)

Vector((1.0, 2.0, 3.0))

In [30]:
for row in m.rows():
    print(row)

Vector((1.0, 2.0, 3.0))
Vector((4.0, 5.0, 6.0))


## Polymorphismus / "Drop-in Replacement"

Vorteil: Wiederverwendung von anderem Code, der auf Sequenzen basiert

In [31]:
import random

In [32]:
random.choice([1, 2, 3, 4, 5, 6])

2

In [33]:
random.choice(v)

3.0

In [34]:
random.choice?

Signature: random.choice(seq)
Docstring: Choose a random element from a non-empty sequence.
File:      /opt/python/versions/3.12.0/lib/python3.12/random.py
Type:      method

In [35]:
# random.choice(m)  # man müsste noch __getitem__ bauen

In [36]:
sum([1, 2, 3, 4, 5, 6])

21

In [37]:
sum((1, 2, 3, 4, 5, 6))

21

In [38]:
sum(v)

6.0

"Die Matrix `m` verhält sich wie eine Liste"

In [39]:
sum(m)

21.0

## Matrix-Vektor Multiplikation

In [40]:
m

Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,)))

In [41]:
+m

Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,)))

In [42]:
-m

Matrix(((-1.0, -2.0, -3.0,), (-4.0, -5.0, -6.0,)))

In [43]:
Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,))) + Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,)))

Matrix(((2.0, 4.0, 6.0,), (8.0, 10.0, 12.0,)))

In [44]:
m + 100

Matrix(((101.0, 102.0, 103.0,), (104.0, 105.0, 106.0,)))

In [45]:
m - 100

Matrix(((-99.0, -98.0, -97.0,), (-96.0, -95.0, -94.0,)))

In [46]:
Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,))) - Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,)))

Matrix(((0.0, 0.0, 0.0,), (0.0, 0.0, 0.0,)))

In [47]:
Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,))) == Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,)))

True