In [1]:
from matrix import Matrix

In [2]:
import numpy as np

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
mat = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

mat

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
10 * mat

array([[10, 20, 30],
       [40, 50, 60]])

In [6]:
Matrix(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,)))

In [7]:
entries = [
        [1, 2, 3],
        [4, 5, 6],
    ]

rows = []

for old_row in entries:
    row = []
    for entry in old_row:
        row.append(float(entry))
    rows.append(tuple(row))

tuple(rows)

((1.0, 2.0, 3.0), (4.0, 5.0, 6.0))

In [8]:
entries = [
        [1, 2, 3],
        [4, 5, 6],
    ]

tuple(tuple(float(entry) for entry in old_row) for old_row in entries)

((1.0, 2.0, 3.0), (4.0, 5.0, 6.0))

In [9]:
m = Matrix(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

m

Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,)))

In [10]:
Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,)))

Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,)))

In [11]:
type(m)

matrix.Matrix

In [12]:
m

Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,)))

In [13]:
len(m)

6

In [14]:
m.n_rows()

2

In [15]:
m.n_cols()

3

In [16]:
len(m._entries[0])

3

In [17]:
m = Matrix([])

RuntimeError: Eine Matrix muss mindestens eine Reihe enthalten!

In [18]:
m = Matrix([[]])

RuntimeError: Eine Matrix muss mindestens eine Spalte enthalten!

In [19]:
m = Matrix([[1], []])

RuntimeError: Jede Reihe muss diesselbe Anzahl an Spalten haben!

In [20]:
m = Matrix(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

m

Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,)))

In [21]:
m.n_rows()

2

In [22]:
m.n_cols()

3